### ISSUE TITLE
KillAura too much sensitive

### ISSUE THREAD

**Issue by Damdamdu95** [ItsMennyo/Flex-AntiCheat#12]
**Which AntiCheat do you use? AAC, AACAdditionPro or AntiAura?**

**AntiCheat**: AAC and AACAdditionPro 

---

**What's the problem? Bypass, False Positive, Bug or Help?**

**Problem**: False Positive

---

**What version does your server use?**

**Server Version**: 1.8.8

---

**Which Minecraft client did you use?**

**Minecraft Client**: 1.8

---

**Which BUILD of Flex do you use?**

**Flex BUILD**: AAC : 3.0.386 BETA and AACAdditionPro : 2.0.235

---

**What is the AntiCheat version itself?**

**AntiCheat Version**: 3.6.4-b1 and 4.6.2

---

**Do you have any proof?**

https://pastebin.com/VNTdQGhY

---

**Try to explain your problem...**

**Description**: 
I was hitting normally and making killaura logs. I was perfectly legit but I was banned. I think KillAura is too much sensitive.

**Comment by ItsMennyo** [comment]
I see a lot of "timing" so can you record a video when you get detected for it so I can see how you pvp? I normally don't get flagged by that check so that sub-check is more sensitive than most other checks.

**Comment by Damdamdu95** [comment]
Sorry, I can't record because I have a bad PC but I pvp the same as the 3rd or 1st of the top https://www.youtube.com/watch?v=L80mvOzKZT8

**Comment by ItsMennyo** [comment]
I will lower the "timing" vaule but this kind of pvping is quite hard for every AntiCheat to account for. Next time you can tweak them a bit by yourself if you get this in the future.

**Comment by Damdamdu95** [comment]
Thank you. I'll take your advice if it happens to me again.

**Comment by ItsMennyo** [comment]
Sure! Logs from servers/players that are really good with pvp will always be handy for overall performance of the config. So maybe in the future, join the Discord server and provide the logs there. The response time is way faster there 😉
