### ISSUE TITLE
AntiKnockback & autoclick issue

### ISSUE THREAD

**Issue by CDGamesYT** [ItsMennyo/Flex-AntiCheat#14]
**Which AntiCheat do you use? AAC, AACAdditionPro or AntiAura?**
AAC
**AntiCheat**: 
AAC
---

**What's the problem? Bypass, False Positive, Bug or Help?**
Bypass and false positive.
**Problem**: 
Sometimes with Antiknockback u get kicked for Velocity and sometimes u get tped but almost all the times nothing happends & when u use autoclick the antihacks does nothing.
---

**What version does your server use?**
spigot 1.8(1.8.8 tested too)
**Server Version**: 
spigot 1.8(1.8.8 tested too)
---

**Which Minecraft client did you use?**
For testing WURST
**Minecraft Client**: 
For testing WURST
---

**Which BUILD of Flex do you use?**
The last one.
**Flex BUILD**: 
The last one.
---

**What is the AntiCheat version itself?**
 3.6.4-b1 
**AntiCheat Version**: 
 3.6.4-b1 
---

**Do you have any proof?**
https://imgur.com/a/iETQrGq
I cant record but you can test it yourself.
**Video or Photo**: 
https://imgur.com/a/iETQrGq
I cant record but you can test it yourself.
---

**Try to explain your problem...**
With a hacked client using antikb sometimes y get tped like 2 blocks away when u get hitted and sometimes u get kicked by Velocity but almost all the times nothing happends.
**Description**: 
With a hacked client using antikb sometimes y get tped like 2 blocks away when u get hitted and sometimes u get kicked by Velocity but almost all the times nothing happends.

**Comment by ItsMennyo** [comment]
Because there are rumors that AAC will get a recode, I will not improve the config for now. With the Velocity issue, you still had AntiKnockback enabled on the screenshot so. Otherwise increase the thresholds of the Velocity check.
