### ISSUE TITLE
Bhop/Speed bypass

### ISSUE THREAD

**Issue by krusic22** [ItsMennyo/Flex-AntiCheat#3]
**Which AntiCheat do you use? AAC or AntiAura?**

**AntiCheat**: AntiAura

---

**What's the problem? Bypass, False Positive, Bug or Help?**

**Problem**: Impact 4.1 bypasses Speed (Bhop)

---

**What version does your server use?**

**Server Version**: 1.11.2 and 1.12.2

---

**Which Minecraft client did you use?**

**Minecraft Client**: Impact 4.1

---

**Which BUILD of Flex do you use?**

**Flex BUILD**: BUILD 1.7.087 BETA

---

**What is the AntiCheat version itself?**

**AntiCheat Version**: 11.18

---

**Do you have any proof?**

**Video or Photo**: Nope.Avi

---

**Try to explain your problem...**

**Description**: Players can bypass using Impacts default Speed settings (Bhop).

**Comment by ItsMennyo** [comment]
Next time if you create a report, make a video so that I can better see how and what. The Speed check works normally. Unfortunately, the AntiAura Speed Check is not very good at the moment. Report this bypass to joehot200 (on Spigot or Discord) to fix it.

**Comment by joehot200** [comment]
Perhaps reducing SpeedLeniency may help. Unfortunately, although I know how the Speed check can be improved now, killaura and ping accounting is my next priority.

**Comment by ItsMennyo** [comment]
Speed check is improved...
