### ISSUE TITLE
Boats and Water is broken

### ISSUE THREAD

**Issue by krusic22** [ItsMennyo/Flex-AntiCheat#4]
Which AntiCheat do you use? AAC or AntiAura?

AntiCheat: AntiAura

What's the problem? Bypass, False Positive, Bug or Help?

Problem: Going into water throws you back. Also boats are fucked.

What version does your server use?

Server Version: 1.11.2 and 1.12.2

Which Minecraft client did you use?

Minecraft Client: Vanilla

Which BUILD of Flex do you use?

Flex BUILD: BUILD 1.7.087 BETA

What is the AntiCheat version itself?

AntiCheat Version: 11.18

Do you have any proof?

Video or Photo: Nope.Avi

Try to explain your problem...

Description: Going into water throws you back. Also boats are fucked.

**Comment by ItsMennyo** [comment]
Unfortunately, I also have these issues with the default config of AntiAura.
So unfortunately this problem has nothing to do with Flex.
Report these issues to joehot200 (on Spigot or Discord).
Changing things to the config does not make sense because this is a code level problem.
