### ISSUE TITLE
Issue on the console

### ISSUE THREAD

**Issue by FunkyNico** [ItsMennyo/Flex-AntiCheat#9]
**Which AntiCheat do you use? AAC, AACAdditionPro or AntiAura?**
AAC, AACAdditonPro
**AntiCheat**: 
AACAdditioPro
---

**What's the problem? Bypass, False Positive, Bug or Help?**
Bug
**Problem**: 
Server Loading Error
---

**What version does your server use?**
CraftBukkit version git-Spigot-2086bb0-8cc5a7e (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
**Server Version**: 
1.12.2
---

**Which Minecraft client did you use?**
Premium
**Minecraft Client**: 
minecraft.net
---

**Which BUILD of Flex do you use?**
Optimized AACAdditionPro
**Flex BUILD**: 
BUILD 1.3.508 BETA
---

**What is the AntiCheat version itself?**
3.10.2
**AntiCheat Version**: 
3.10.2
---

**Do you have any proof?**
https://hastebin.com/ajinupofuj.css
**Video or Photo**: 
https://imgur.com/a/vIOAUaQ
---

**Try to explain your problem...**
When the server start, and load the accaditionpro config, in the end appears a server loading error, because "Config-Section is null when loading: InventoryChat.thresholds"
**Description**: 
Pls help :D.

**Comment by ItsMennyo** [comment]
As you can see at the top, the config version that you use is for AACAdditionPro version 3.13.1 and will not work on 3.10.2 because of some changes that Photon made. Update AACAdditonPro or downgrade to Flex BUILD 1.3.314 BETA.
